# Uncomment the next line to define a global platform for your project
 platform :ios, '8.3'

target '36074' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 36074
pod 'Kingfisher', '~> 3.0'

end
